server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zzw999/config
          clone-on-start: true
        encrypt:
          enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8181/eureka/
