eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8184
spring:
  application:
    name: zuul
zuul:
  routes:
    api-a:
      path: /feign/**
      serviceId: manage
    api-b:
      path: /manage/**
      serviceId: manage